# Generated by Django 5.2.2 on 2025-06-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enrollment_updated_by_enrollment_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
