# Generated by Django 5.2.2 on 2025-06-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
