# Generated by Django 5.2.2 on 2025-06-20 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_enrollment_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial_success', 'Partial_success'), ('failure', 'Failure'), ('uploading', 'Uploading')], default='uploading', max_length=20)),
                ('file_name', models.CharField(max_length=100)),
                ('total_record', models.IntegerField()),
                ('success_count', models.IntegerField()),
                ('failure_count', models.IntegerField()),
                ('remarks', models.TextField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
