# Generated by Django 5.2.2 on 2025-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bulkuploadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkuploadstatus',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
